### PR TITLE
Modify Page for Accessibility

### PR DESCRIPTION
**Pull request by AbrahaKahsay**

### CODE REVIEW

**Comment by Retky** [comment]
> This branch modify the display of the page, for accessibility.

## Points that have been checked:
- **Page titles** || No issues were found

- **Image text alternatives** || No issues were found

- **Text headings** ||  No issues were found

- **Color contrast** || Isssue:
   - Orange Buttons
   - Works boxes text

- **Resize** || No issues were found

- **Interaction** || Issue:
  - Labels were added to the form elements

- **Moving content** || No issues were found

- **The basic structure of the page** || No issues were found

**Review by gemmen29 — CHANGES_REQUESTED** [review]
Hi @AbrahaKahsay and @Retky, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- You did a great job by mentioning that you checked all points but kindly add the result of the check. for example Page title: Fixed issues or No issues found. Kindly add the result for each point.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Retky** [comment]
Thanks @gemmen29 😄 
For the review. I have made the required changes.

**Review by gemmen29 — APPROVED** [review]
Hi @AbrahaKahsay and @Retky, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
